version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
      POSTGRES_DB: stockdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: .
    environment:
      DATABASE_URL: postgres://stock:stock@db:5432/stockdb
      SECRET_KEY: changeme
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "3000:3000"
volumes:
  postgres-data:
